---

- hosts: vagrant
  become: true
  roles:
    - common
    - sshd

- hosts: vuls_centos
  become: true
  roles:
    - vuls
    - vuls_repo

- hosts: mac
  connection: local
  gather_facts: no
  roles:
    - vuls_mac
