---

- name: edit sshd_config (PasswordAuthentication)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    insertafter: EOF
    state: present

- name: edit sshd_config (ChallengeResponseAuthentication)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    insertafter: EOF
    state: present

- name: edit sshd_config (PermitRootLogin)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    insertafter: EOF
    state: present
  notify: reload sshd service

- name: sudo NOPASS
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: edit /etc/pam.d/su
  lineinfile:
    path: /etc/pam.d/su
    regexp: 'auth\s+required\s+pam_wheel.so\s+use_uid'
    value: 'auth required pam_wheel.so use_uid'
    insertafter: EOF
    state: present
